version: '3'

services:
  db:
    image: rsvp-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - <Absolute path to data directory>:/var/lib/mysql
    networks:
      - rsvpnetwork

  app:
    image: rsvp-service
    restart: always
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/rsvp?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    depends_on:
      - db
    networks:
      - rsvpnetwork

networks:
  rsvpnetwork:
    driver: bridge
